### ISSUE TITLE
__init__.py in sge-pygame is a bit too big

### ISSUE THREAD

**Issue by mrshu** [coppolaemilio/StellarGameEngine#4]
Well, I'm not sure if it's intentional but 4683 lines of code is a bit too much. At least for someone not familiar with the code but interested in helping out.

How about splitting it into a few more files?

**Comment by onpon4** [comment]
Yeah, I agree, and I'll work on this. It's all in **init**.py because it was written from the beginning with no regard for multiple files, which was clearly a mistake. I might even end up modifying the specification so it works more intuitively with several modules.

**Comment by mrshu** [comment]
Great! 

Keep up the great work you do at Stellar!

**Comment by onpon4** [comment]
Alright, as of b33448afb0 SGE is now finally split into multiple files (for both the Pygame implementation and the template). Luckily, I didn't have to break compatibility.
